"""uuid for user

Revision ID: b023e4b93269
Revises: 2a493ef0b258
Create Date: 2025-02-04 14:28:05.761104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b023e4b93269"
down_revision: Union[str, None] = "2a493ef0b258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "uuid", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "uuid", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
