"""uuid for user

Revision ID: 2a493ef0b258
Revises: 9cb7cc01bfd2
Create Date: 2025-02-04 14:19:58.976465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a493ef0b258"
down_revision: Union[str, None] = "9cb7cc01bfd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("uuid", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###
