"""querty

Revision ID: 5a222dfe9824
Revises: d1fd130c747f
Create Date: 2025-01-10 17:03:08.897498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a222dfe9824"
down_revision: Union[str, None] = "d1fd130c747f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "promocode", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "promocode", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
