"""add column count

Revision ID: 4fd37482a540
Revises: 5a222dfe9824
Create Date: 2025-01-10 18:30:59.155958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4fd37482a540"
down_revision: Union[str, None] = "5a222dfe9824"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    op.alter_column(
        "orders", "promocode", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "promocode", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("order_product_association", "count")
    # ### end Alembic commands ###
