"""querty

Revision ID: b90dd9a9b7c8
Revises: 5a222dfe9824
Create Date: 2025-01-10 18:25:39.242780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b90dd9a9b7c8"
down_revision: Union[str, None] = "5a222dfe9824"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "promocode", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "promocode", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
